### ISSUE TITLE
An unhandled exception occurred while checking for vulnerabilities: 500 InternalServerError

### ISSUE THREAD

**Issue by mcallaghan-bsm** [fabiano/dotnet-ossindex#11]
hello!
we started getting this
``` 
dotnet-ossindex --username USER --api-token TOKEN OurSolution.sln

> Solution: /builds/dev/SNIP
  12 project(s) found
> Project: /builds/dev/SNIP
  An unhandled exception occurred while checking for vulnerabilities: 500 InternalServerError 
```

**Comment by mcallaghan-bsm** [comment]
No way it seems to get additional verbosity from that.
I confirmed I can still login to sonatype oss w/ these credentials & the API keep seems valid.

**Comment by fabiano** [comment]
Hi @mcallaghan-bsm.

It looks like the `user-agent` header is required now. I'll add it and push a new version later today.

Thank you for letting me know about this bug.

**Comment by mcallaghan-bsm** [comment]
thx! sounds good

**Comment by fabiano** [comment]
Pushed the new version: https://www.nuget.org/packages/dotnet-ossindex/0.5.0

Thank you again.

**Comment by mcallaghan-bsm** [comment]
VERIFIED! 
Thank you for a fast turnaround @fabiano 

```
$ dotnet tool install --global dotnet-ossindex
You can invoke the tool using the following command: dotnet-ossindex
Tool 'dotnet-ossindex' (version '0.5.0') was successfully installed.
...
(snip)
...
Job succeeded
```
