### ISSUE TITLE
Request: Support .NET 5.0

### ISSUE THREAD

**Issue by jeremyhayes** [fabiano/dotnet-ossindex#13]
When running in an environment with only .NET 5 SDK available, get the following error:

```
 $> dotnet ossindex ./Redacted.sln
 It was not possible to find any compatible framework version
 The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
   - The following frameworks were found:
       5.0.3 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]
 
 You can resolve the problem by installing the specified framework and/or SDK.
```

Are there plans to release an update to support .NET 5.0? Happy to submit a PR for this if needed.

**Comment by fabiano** [comment]
@jeremyhayes I upgraded it last week. Let me push the code and release a new version of the package.

**Comment by fabiano** [comment]
@jeremyhayes New version released: https://www.nuget.org/packages/dotnet-ossindex/0.6.0

**Comment by jeremyhayes** [comment]
Nice! 🎉 

Thanks @fabiano!
