### ISSUE TITLE
Suddenly dotnet-ossindex is incompatible with netcoreapp3.1

### ISSUE THREAD

**Issue by mcallaghan-geotab** [fabiano/dotnet-ossindex#15]
Hi!

We've been running this `dotnet-ossindex` tool for many months against .NETcore 3.1.

Suddenly (starting last night), we receive:
```
error NU1202: Package dotnet-ossindex 0.6.0 is not compatible with netcoreapp3.1 (.NETCoreApp,Version=v3.1) / any. Package dotnet-ossindex 0.6.0 supports: net5.0 (.NETCoreApp,Version=v5.0)
```

We install it dynamically using:
```
        - export PATH="$PATH:/root/.dotnet/tools"
        - dotnet tool install --global dotnet-ossindex
```

other messages/notes from the error:
```
The tool package could not be restored.
Tool 'dotnet-ossindex' failed to install. This failure may have been caused by:
* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.
For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

**Comment by fabiano** [comment]
Hi, I release a new version yesterday upgrading it to use the .NET 5.0. You can install the previous version using the command:

> dotnet tool install --global dotnet-ossindex --version 0.5.0

**Comment by mcallaghan-geotab** [comment]
Agreed (that is the workaround).  Is it the plan/intention that the newest release won't be compatible with previous framework versions?  (so no new fixes/changes should be expected every again to the tool for .NET core 3.1?)

**Comment by fabiano** [comment]
No, I need to change the project to include support for more than one .NET version.

The dotnet-outdated tool does that, so it should not be hard to do the same.
