### ISSUE TITLE
Support .NET 6.0?

### ISSUE THREAD

**Issue by nevind7** [fabiano/dotnet-ossindex#23]
Hello!

Dotnet 3.1 and 5.0 are nearing their end of support dates soon. Do you know when support for 6.0 will be available?

Thanks!

**Comment by fabiano** [comment]
Hi, the latest version (v0.6.0) already supports .NET 6.0. You can install it using:

> dotnet tool install --global dotnet-ossindex --version 0.6.0

I'll start working in the .NET 7.0 support soon.

**Comment by fabiano** [comment]
My mistake. I forgot to push v0.7.0 with the .NET 6.0 support. Just did that.

**Comment by nevind7** [comment]
Awesome, thank you! Closing.
