### ISSUE TITLE
pending release to support .NET 3.1?

### ISSUE THREAD

**Issue by mcallaghan-bsm** [fabiano/dotnet-ossindex#6]
Hello!

PER https://github.com/fabiano/dotnet-ossindex/commit/9d969ee820b20eeb82a0f0164260d1f452445cbd, commit was added to support .NET 3.1.

```
$ dotnet-ossindex
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.2.0' was not found.
  - The following frameworks were found:
      3.1.4 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

dotnet tool list --global | grep ossindex
dotnet-ossindex      0.2.0        dotnet-ossindex
```

Don't see a new release for 2020 yet; 
https://github.com/fabiano/dotnet-ossindex/releases
(ETA? :o)

**Comment by fabiano** [comment]
Hi, I was finishing a fix to support output redirection. I just submitted a new version with the .NET 3.1 support: https://www.nuget.org/packages/dotnet-ossindex/0.3.0
